//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookReviews.Reviews
{


    public partial class ReviewPage
    {

        /// <summary>
        /// ReviewLikes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookReviews.Reviews.Components.ReviewLikes ReviewLikes;

        /// <summary>
        /// VisibilityControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookReviews.Auth.Controls.VisibilityControl VisibilityControl1;

        /// <summary>
        /// VisibilityControl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookReviews.Auth.Controls.VisibilityControl VisibilityControl2;

        /// <summary>
        /// BookPreview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookReviews.Books.Components.BookPreview BookPreview;

        /// <summary>
        /// RatingInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookReviews.Components.RatingInput RatingInput;

        /// <summary>
        /// ReviewsDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource ReviewsDataSource;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new BookReviews.Main Master
        {
            get
            {
                return ((BookReviews.Main)(base.Master));
            }
        }
    }
}
